version: "3"
services:
    app:
        container_name: python
        image: exercice/python
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            FLASK_APP: autoapp.py
            DATABASE_URL: postgresql://root:password@db/pythonapp
            FLASK_DEBUG: 0
        ports:
            - "8443:5000"
        depends_on:
            - db
        restart: always

    db:
        container_name: db
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pythonapp
            POSTGRES_USER: root
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        restart: always